version: 2.0

jobs:
    build:
        docker:
            - image: circleci/python:3.7
        steps:
            - checkout
            - restore_cache:
                key: cache-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            - run: pipenv install --dev --deploy
            - save_cache:
                key: cache-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
                paths:
                    - "/home/circleci/.local/share/virtualenvs"
            - run: pipenv run build --to html --log-level DEBUG
            - store_artifacts:
                path: Notebook.html
                destination: Notebook.html
